### PR TITLE
Feat/header

### PR DESCRIPTION
**Pull request by Laeti013**
Create header for the application Marseille Unité Spéciale

### CODE REVIEW

**Review by Childbutsmart — CHANGES_REQUESTED** [review]
should use MUI library

**Review by Emmanuelle-S — APPROVED** [review]

**Review by Guillaume1804 — APPROVED** [review]
Make sure to merge feat/header into dev and not main

**Review by Thesirix — CHANGES_REQUESTED** [review]
mui

**Comment by Emmanuelle-S** [comment]
On ne va pas merger cette pullrequest car on va passer par MUI :)

**Pull request closed without merging**
