### PR TITLE
Feat/worldMap

### PR DESCRIPTION
**Pull request by Childbutsmart**
Transcription of the response to the API request in JSON format which allowed the addition of markers, 
Attempt to fix the showMyLocation functionality without success,
Add icons in svg format.

### CODE REVIEW

**Review by Thesirix — APPROVED** [review]
ok

**Review by Thesirix — APPROVED** [review]
ok

**Review by Thesirix — APPROVED** [review]
ok

**Review by Guillaume1804 — APPROVED** [review]
Approuvé !

**Review by Emmanuelle-S — APPROVED** [review]
well done

**Pull request merged**
